#! /bin/bash
#
# Author: Bartosz Zawadka, 2015
#
# Contact: kontakt@bartoszzawadka.pl
#
# /etc/init.d/recorder-service
#
### BEGIN INIT INFO
# Provides: recorder-service
# Required-Start: $remote_fs $syslog $network
# Required-Stop: $remote_fs $syslog $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Pi Cam Supervisor - Recorder service
# Descirption: Alarm system video recording signals listener service
### END INIT INFO

PIDFILE=/var/run/recorder-service.pid
USER=root
CHUID=root
STARTAS=/usr/bin/python
ARGS=/usr/local/picamsupervisor/recorder_service/recorder_service.pyc
RTIME=10

case "$1" in
	start)
		echo "Starting PiCamSupervisor - Recorder service"
		sudo start-stop-daemon --start --pidfile $PIDFILE --make-pidfile --user $USER --chuid $CHUID --background --startas $STARTAS -- $ARGS
		;;
	stop)
		echo "Stopping PiCamSupervisor - Recorder service"
		sudo start-stop-daemon --stop --pidfile $PIDFILE --retry $RTIME
		;;
	restart)
		echo "Restarting PiCamSupervisor - Recorder service"
		$0 stop
		$0 start
		;;
	*)
		echo "Invalid command. Usage: /etc/init.d/recorder-service {start|stop|restart}"
		exit 1
		;;
esac
exit 0

